# Generated by Django 4.2.2 on 2023-06-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='电话号码'),
        ),
    ]
