# Generated by Django 4.2.2 on 2023-06-11 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phonenumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('caller', models.CharField(max_length=15, verbose_name='主叫号码')),
                ('callee', models.CharField(max_length=15, verbose_name='被叫号码')),
                ('block', models.BooleanField(default=False, verbose_name='是否拦截')),
                ('request_ip', models.CharField(max_length=15, verbose_name='请求IP')),
            ],
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='tags',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
